Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -41,11 +41,11 @@ jobs:
    - name: Check Bandit Results 
      id: bandit-check
      run: |
-      #if [ -f bandit_results.json ]; then
+      if [ -f bandit_results.json ]; then
       # Ищем в отчете результаты с высоким уровнем серьезности (HIGH)
       # if jq -e '.results[] | select(.issue_confidence == "HIGH" and .issue_severity == "HIGH")' bandit_results.json; then
-      #  echo "Bandit found critical vulnerabilities! Failing the pipeline."
-      #  exit 1 # Завершаем шаг с ошибкой, что заставит пайплайн "упасть"
+        echo "Bandit found critical vulnerabilities! Failing the pipeline."
+        exit 1 # Завершаем шаг с ошибкой, что заставит пайплайн "упасть"
       # else
       #  echo "No critical vulnerabilities found by Bandit." 
       #  fi 
