Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -32,24 +32,24 @@ jobs:
       # || true - это костыль, чтобы шаг не "падал" при найденных уязвимостях.
       # Мы обработаем результат на следующем шаге.
       # Шаг 4.1: Анализируем отчет Bandit и "валим" пайплайн при критических уязвимостях
-  - name: Check Bandit Results
-    id: bandit-check
-    run: |
-     if [ -f bandit_results.json ]; then
-     # Ищем в отчете результаты с высоким уровнем серьезности (HIGH)
-     if jq -e '.results[] | select(.issue_confidence == "HIGH" and .issue_severity == "HIGH")' bandit_results.json; then
-      echo "Bandit found critical vulnerabilities! Failing the pipeline."
-      exit 1 # Завершаем шаг с ошибкой, что заставит пайплайн "упасть"
-     else
-      echo "No critical vulnerabilities found by Bandit."
-      fi
+   - name: Check Bandit Results
+     id: bandit-check
+     run: |
+      if [ -f bandit_results.json ]; then
+      # Ищем в отчете результаты с высоким уровнем серьезности (HIGH)
+      if jq -e '.results[] | select(.issue_confidence == "HIGH" and .issue_severity == "HIGH")' bandit_results.json; then
+       echo "Bandit found critical vulnerabilities! Failing the pipeline."
+       exit 1 # Завершаем шаг с ошибкой, что заставит пайплайн "упасть"
       else
-      echo "Bandit report not found. Assuming no issues."
-      fi
-  # Шаг 5: Запускаем сканер зависимостей Trivy
-  - name: Run Trivy vulnerability scanner
-    uses: aquasecurity/trivy-action@master
-    with:
+       echo "No critical vulnerabilities found by Bandit."
+       fi
+       else
+       echo "Bandit report not found. Assuming no issues."
+       fi
+   # Шаг 5: Запускаем сканер зависимостей Trivy
+   - name: Run Trivy vulnerability scanner
+     uses: aquasecurity/trivy-action@master
+     with:
      scan-type: 'fs'
      scan-ref: '.'
      format: 'table'
